### ISSUE TITLE
default to --stringify when converting from YAML to JSON

### ISSUE THREAD

**Issue by cdepillabout** [remarshal-project/remarshal#53]
In one of my projects, I use `remarshal` with a bash script convert a YAML file to a JSON file.

I was quite surprised to have a user submit a bug about `remarshal` failing to convert a YAML file because it can't output a `datetime` value to JSON: https://github.com/cdepillabout/stacklock2nix/pull/55

When converting from YAML to JSON, I can't really imagine a use-case for `--stringify` not to be the default.  What sort of user knows that they want to output JSON, but actively wants the conversion process to fail on dates?

If you don't want to change the defaults around `--stringify`, it might be nice to call this out prominently in the README and/or `--help` output, and suggest that users going from YAML to JSON should always(?) use `--stringify`.

**Comment by dbohdan** [comment]
I agree this is what a user who converts YAML to JSON normally wants. I didn't make it the default because the default policy for Remarshal is to not lose information, i.e., to convert so a round-trip is lossless.

I have explained this limitation and the reasoning behind it in https://github.com/remarshal-project/remarshal/blob/96fbdb956c431f967836ae7c9aea13205ed0b877/README.md#lossless-by-default-lossy-must-be-enabled. Would you say this is a sufficient explanation?

**Comment by dbohdan** [comment]
The update to the documentation has been merged.
